### ISSUE TITLE
batch_size的问题

### ISSUE THREAD

**Issue by Caofei2023** [zhaoshan2/pangu-pytorch#12]
您好，非常感谢您的工作。当我想改变batch_size为2时遇到了一些问题。
当训练batch_size=1时，训练可以完整通过、运行。
但batch_size为2时，pangu_model.py layers.py中出现了tensor运算过程中形状对不上的情况。非常感谢、期待您的回答！

**Comment by zhaoshan2** [comment]
你好, 代码中存在一些hard code, 比如
[` x_shifted = attn_windows.view(1, attn_windows.shape[0], Z // self.window_size[0], H // self.window_size[1] + 1, self.window_size[0], self.window_size[1], self.window_size[2], -1)#1,30,4,31,2,6,12,192`](https://github.com/zhaoshan2/pangu-pytorch/blob/97db96bc9c039cd7fd3e3330bcd3b536c8b446cf/models/layers.py#L227)
只考虑了batch size=1的情况，您可以根据需要调整

**Comment by Caofei2023** [comment]
感谢您的回答，问题得到了解决，祝您工作顺利、生活开心。
