### ISSUE TITLE
有关pangu的.pth文件问题

### ISSUE THREAD

**Issue by lz010866** [zhaoshan2/pangu-pytorch#6]
在您附有的Hugging Faces链接上pretrain_model.zip的文件下有一个.pth文件，请问是继承了盘古官方发布的onnx格式的权重吗？或者是微调又训练保存的模型文件？这个.pth文件和盘古原模型有一样的效果吗？

**Comment by lz010866** [comment]
谢谢您，我想知道您是怎么把onnx转为.pth格式的，因为我用onnx2torch库，转成pytorch模型，遇到一些问题，不能完全转为torch模型，模型中依然是onnx的各种层，而不是我期待的linear层、卷积层、embedding层等
<img width="776" alt="微信图片_20240726230008" src="https://github.com/user-attachments/assets/4b91b1a4-638c-4615-9bb6-e9477c4ec85f">
<img width="772" alt="微信图片_20240726230230" src="https://github.com/user-attachments/assets/f1c5f9ea-5632-4650-aed3-fe627d1e3d44">

**Comment by zhaoshan2** [comment]
你好，我们是首先复现了模型，之后检查了onnx文件和复现模型之间的关系并加载权重。

**Comment by lz010866** [comment]
好呢，非常感谢您的回复！谢谢您
