### ISSUE TITLE
Questions about AuxiliaryData

### ISSUE THREAD

**Issue by weiyf2001** [zhaoshan2/pangu-pytorch#7]
In the paper, we know that the inputs consist of three parts x_surface, x_upper and x_ocis.However, in the code, there are five parts of input, and I would like to ask what the meaning of statistics, maps, and const_h represents.

**Comment by zhaoshan2** [comment]
This repository includes only the reimplementation of the Pangu model in PyTorch, and therefore does not utilize x_oci. The related constants, such as statistics, maps, and constant_h, are extracted from the original ONNX weights. These constants represent the mean and standard deviation of long-term weather conditions, static masks (e.g., topology and land-ocean masks), and padding values. They are included to ensure that the results align precisely with those reported in the original paper.

**Comment by weiyf2001** [comment]
Thank you for your insightful response.It has greatly enhanced my understanding of the topic.
