### ISSUE TITLE
Blank output results 

### ISSUE THREAD

**Issue by winniechj** [zhaoshan2/pangu-pytorch#8]
Thanks author for providing the pytorch version model.
I've executed it smoothly without error but no output in the generated csv files. 
Could you please check with the problem?
Thank you!
<img width="212" alt="pangu_result" src="https://github.com/user-attachments/assets/eee934d2-e9ab-4480-a924-377b0e0f33ea">
<img width="482" alt="pangu_out_acc_surface" src="https://github.com/user-attachments/assets/66b70bed-ff49-4a31-9a49-1a94149377f5">

**Comment by zhaoshan2** [comment]
Hi,
It looks like the model didn’t generate the expected output. Which file are you running? Also, is there any figure output?

**Comment by winniechj** [comment]
I'm running test_main.py, and no images produced.

**Comment by zhaoshan2** [comment]
I checked again and the output looks fine to me. It is probably becasue the input of the model is empty. 
Could you check if the program reads the input correctly? 
[`input_test, input_surface_test, target_test, target_surface_test, periods_test = data`](https://github.com/zhaoshan2/pangu-pytorch/blob/17d278d4a18250329860899ab4521bf2eae768e8/models/pangu_sample.py#L194C9-L194C94)

**Comment by winniechj** [comment]
Sorry, this problem no longer occurs, I will close this issue.

**Comment by winniechj** [comment]
Sorry, this problem no longer occurs, I will close this issue.

**Comment by dadada-111** [comment]
Why is it that when I run the reasoning steps, I only get the data of one grid point? Shouldn't it be as many as 721×1440 grid points?
